### PR TITLE
Extend OutgoingMessage class with native implementation of OutgoingMessage from node http module

### PR DESCRIPTION
**Pull request by maktwin**
While running express app in the second azure functions runtime I got several errors like: 
```
TypeError: cannot read `content-type` on undefined.
```

In this PR OutgoingMessage inherits methods and properties from node `http` OutgoingMessage module.

### CODE REVIEW

**Comment by yvele** [comment]
Hey @maktwin thank you! That looks pretty good.

I don't know why I haven't thought about  inheriting from the native `OutgoingMessage` prototype.

Have you tested the code in a real Azure Functions integration?

What do you mean by _second_ Azure Functions runtime?

**Comment by maktwin** [comment]
Hi @yvele, yes I have tested code in a real Azure Functions integration.
 
There are two major versions of the Azure Functions runtime: 1.x and 2.x. Only 1.x is approved for production use. The 2.x version is in preview right now.

Please, follow this link to get more info: https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions

**Comment by yvele** [comment]
Thank you @maktwin, may I ask you what exact version of node are you using on production within Azure Functions?

I'm [thinking about supporting node 8 and 10](https://github.com/yvele/azure-function-express/issues/19#issuecomment-417846338) (with unit tests, etc.)

**Comment by maktwin** [comment]
Hey @yvele,
node version 10.8.0

**Comment by yvele** [comment]
I've pulled your branch, and running unit tests (`npm run validate`) with node 6.11.2 everything is passing.

But tests are failing with node 10.8.0

```
 FAIL  test/ExpressAdapter.test.js
  ● ExpressAdapter › Should work

    expect(received).toEqual(expected)

    Expected value to equal:
      {"body": "body", "headers": undefined, "isRaw": true, "status": 200}
    Received:
      {"body": "body", "headers": {}, "isRaw": true, "status": 200}

    Difference:

    - Expected
    + Received

      Object {
        "body": "body",
    -   "headers": undefined,
    +   "headers": Object {},
        "isRaw": true,
        "status": 200,
      }

      at Object.done (test/ExpressAdapter.test.js:25:29)
      at OutgoingMessage.end (src/OutgoingMessage.js:32:11)
      at ExpressAdapter.<anonymous> (test/ExpressAdapter.test.js:15:11)
      at ExpressAdapter.emit (events.js:182:13)
      at ExpressAdapter.handleAzureFunctionRequest (src/ExpressAdapter.js:72:59)
      at Object.<anonymous> (test/ExpressAdapter.test.js:36:5)
          at new Promise (<anonymous>)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● ExpressAdapter › Should work with a buffer

    expect(received).toEqual(expected)

    Expected value to equal:
      {"body": "body", "headers": undefined, "isRaw": true, "status": 200}
    Received:
      {"body": "body", "headers": {}, "isRaw": true, "status": 200}

    Difference:

    - Expected
    + Received

      Object {
        "body": "body",
    -   "headers": undefined,
    +   "headers": Object {},
        "isRaw": true,
        "status": 200,
      }

      at Object.done (test/ExpressAdapter.test.js:57:29)
      at OutgoingMessage.end (src/OutgoingMessage.js:32:11)
      at ExpressAdapter.<anonymous> (test/ExpressAdapter.test.js:47:11)
      at ExpressAdapter.emit (events.js:182:13)
      at ExpressAdapter.handleAzureFunctionRequest (src/ExpressAdapter.js:72:59)
      at Object.<anonymous> (test/ExpressAdapter.test.js:68:5)
          at new Promise (<anonymous>)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 PASS  test/expressIntegration.test.js
 PASS  test/OutgoingMessage.test.js
 PASS  test/IncomingMessage.test.js
 PASS  test/main.test.js

Test Suites: 1 failed, 4 passed, 5 total
Tests:       2 failed, 17 passed, 19 total
Snapshots:   0 total
Time:        0.808s, estimated 1s
Ran all test suites.


```

Aren't you using node 10.8.0? 🤔

**Comment by maktwin** [comment]
hi @yvele,
I make it work on node 10 and it also works with node 6. But yeah, tests are working on node 6.

I can help to contribute with tests etc in next PR's

**Pull request merged**
