### PR TITLE
Fix for issue 27 support for log, info,error, warn and verbose methods of context objects 

### PR DESCRIPTION
**Pull request by SwapnilBhosale**
#27 Fix for issue 27 support for log, info,error, warn and verbose methods of context objects 

1) Do not add explicit handling for log function in sanitizeContext method
2) remove log related test cases
3) Tested on Azure and now able to log with all the levels specified

image

### CODE REVIEW

**Comment by yvele** [comment]
Why has you closed this?

**Comment by SwapnilBhosale** [comment]
Actually travis job was failed due to no space after json key name and
colon.
So I closed this PR #28

I didn't saw that tab spacing is affected with my commit, apologies.
Iwill fix that in future.

**Comment by yvele** [comment]
You don't have to re-open a PR to fix a commit.. you only have to re-commit in the branch..

**Comment by SwapnilBhosale** [comment]
Yup, I missed it.
Apologies.

**Pull request closed without merging**
